config/routes.rb
Rails.application.routes.draw do
  get '/prompts/search', to: 'prompts#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "prompts#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_prompt.rb
class UserPrompt < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :prompt, type: 'text'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['prompt']
          }
        }
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController

  def search
    if params[:text]
      @prompts = UserPrompt.search(params[:text])
      UserPrompt.create!(text: params[:text])
    end
    @searches = UserPrompt.order(created_at: :desc).limit(5)
  end
end

app/controllers/user_prompts_controller.rb
class UserPromptsController < ApplicationController

  def search
    if params[:text]
      @prompts = UserPrompt.search(params[:text])
      UserPrompt.create!(text: params[:text])
    end
    @searches = UserPrompt.order(created_at: :desc).limit(5)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticPrompt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prompts/search.html.erb
<h1>Search Prompts</h1>
<%= form_tag prompts_search_path, method: :get, id: 'search-form' do %>
  <%= text_field_tag :text, params[:text], placeholder: "Enter search terms" %>
  <%= submit_tag "Search" %>
<% end %>

<h1>Results:</h1>
<% @prompts&.each do |prompt| %>
  <p>Search: <i><%= prompt._index %></i></p>
  <p>Score: <i><%= prompt._score %></i></p>
  <p>Id: <i><%= prompt._id %></i></p>
  <p>Content: <i><%= prompt._source['prompt'] %></i></p>
  <hr>
<% end %>

<h1>Last Five Search Queries:</h1>
<% @searches&.each do |search| %>
  <p>Search query: <i><%= search.text %></i></p>
<% end %>

app/views/user_prompts/search.html.erb
<h1>Search Prompts</h1>
<%= form_tag user_prompts_search_path, method: :get, id: 'search-form' do %>
  <%= text_field_tag :text, params[:text], placeholder: "Enter search terms" %>
  <%= submit_tag "Search" %>
<% end %>

<h1>Results:</h1>
<% @prompts&.each do |prompt| %>
  <p>Search: <i><%= prompt._index %></i></p>
  <p>Score: <i><%= prompt._score %></i></p>
  <p>Id: <i><%= prompt._id %></i></p>
  <p>Content: <i><%= prompt._source['prompt'] %></i></p>
  <hr>
<% end %>

<h1>Last Five Search Queries:</h1>
<% @searches&.each do |search| %>
  <p>Search query: <i><%= search.text %></i></p>
<% end %>